// Customers Actions (Async)
export const FETCH_CUSTOMERS_PARTICULAR_INIT = 'FETCH_CUSTOMERS_PARTICULAR_INIT'
export const FETCH_CUSTOMERS_ENTERPRISE_INIT = 'FETCH_CUSTOMERS_ENTERPRISE_INIT'
export const FETCH_CUSTOMERS_SUCCESS = 'FETCH_CUSTOMERS_SUCCESS'
export const FETCH_CUSTOMERS_FAILURE = 'FETCH_CUSTOMERS_FAILURE'
export const CREATE_CUSTOMER_INIT = 'CREATE_CUSTOMER_INIT'
export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS'
export const CREATE_CUSTOMER_FAILURE = 'CREATE_CUSTOMER_FAILURE'
export const UPDATE_CUSTOMER_INIT = 'UPDATE_CUSTOMER_INIT'
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS'
export const UPDATE_CUSTOMER_FAILURE = 'UPDATE_CUSTOMER_FAILURE'

// Customers Actions (sync)
export const RESET_STATE_CUSTOMER_EDITED = 'RESET_STATE_CUSTOMER_EDITED'
export const UPDATE_STATE_CUSTOMER = 'UPDATE_STATE_CUSTOMER'

// expandRow Actions (sync)
export const LOAD_STATE_EXPAND = 'LOAD_STATE_EXPAND'
export const UPDATE_STATE_EXPAND = 'UPDATE_STATE_EXPAND'
export const RESET_STATE_EXPAND_EDITED = 'RESET_STATE_EXPAND_EDITED'

// expandRow Actions (async)
export const UPDATE_CUSTOMER_EXPAND_INIT = 'UPDATE_CUSTOMER_EXPAND_INIT'
export const UPDATE_CUSTOMER_EXPAND_SUCCESS = 'UPDATE_CUSTOMER_EXPAND_SUCCESS'
export const UPDATE_CUSTOMER_EXPAND_FAILURE = 'UPDATE_CUSTOMER_EXPAND_FAILURE'

// pricesList Actions (Async)
export const FETCH_PRICESLIST_INIT = 'FETCH_PRICESLIST_INIT'
export const FETCH_PRICESLIST_SUCCESS = 'FETCH_PRICESLIST_SUCCESS'
export const FETCH_PRICESLIST_FAILURE = 'FETCH_PRICESLIST_FAILURE'
export const UPDATE_PRICESLIST_INIT = 'UPDATE_PRICESLIST_INIT'
export const UPDATE_PRICESLIST_SUCCESS = 'UPDATE_PRICESLIST_SUCCESS'
export const UPDATE_PRICESLIST_FAILURE = 'UPDATE_PRICESLIST_FAILURE'
export const CREATE_PRICESLIST_INIT = 'CREATE_PRICESLIST_INIT'
export const CREATE_PRICESLIST_SUCCESS = 'CREATE_PRICESLIST_SUCCESS'
export const CREATE_PRICESLIST_WARNING = 'CREATE_PRICESLIST_WARNING'
export const CREATE_PRICESLIST_FAILURE = 'CREATE_PRICESLIST_FAILURE'

// pricesList Actions (sync)
export const RESET_STATE_PRICESLIST_EDITED = 'RESET_STATE_PRICESLIST_EDITED'
export const UPDATE_STATE_PRICESLIST = 'UPDATE_STATE_PRICESLIST'


//Articles Actions(Async)
export const FETCH_ARTICLES_INIT = 'FETCH_ARTICLES_INIT'
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS'
export const FETCH_ARTICLES_FAILURE = 'FETCH_ARTICLES_FAILURE'
export const UPDATE_ARTICLES_INIT = 'UPDATE_ARTICLES_INIT'
export const UPDATE_ARTICLES_SUCCESS = 'UPDATE_ARTICLES_SUCCESS'
export const UPDATE_ARTICLES_FAILURE = 'UPDATE_ARTICLES_FAILURE'


//Articles Actions(sync)
export const UPDATE_SELECT_ROW = 'UPDATE_SELECT_ROW'


//Delivery notes Actions(Async)
export const FETCH_DELIVERYNOTES_INIT = 'FETCH_DELIVERYNOTES_INIT'
export const FETCH_DELIVERYNOTES_SUCCESS = 'FETCH_DELIVERYNOTES_SUCCESS'
export const FETCH_DELIVERYNOTES_FAILURE = 'FETCH_DELIVERYNOTES_FAILURE'


//Payments Actions(Async)
export const FETCH_PAYMENTS_INIT = 'FETCH_PAYMENTS_INIT'
export const FETCH_PAYMENTS_SUCCESS = 'FETCH_PAYMENTS_SUCCESS'
export const FETCH_PAYMENTS_FAILURE = 'FETCH_PAYMENTS_FAILURE'

