// Customers Actions (Async)
export const FETCH_CUSTOMERS_PARTICULAR_INIT = 'FETCH_CUSTOMERS_PARTICULAR_INIT'
export const FETCH_CUSTOMERS_ENTERPRISE_INIT = 'FETCH_CUSTOMERS_ENTERPRISE_INIT'
export const FETCH_CUSTOMERS_SUCCESS = 'FETCH_CUSTOMERS_SUCCESS'
export const FETCH_CUSTOMERS_FAILURE = 'FETCH_CUSTOMERS_FAILURE'
export const SAVE_CUSTOMER_INIT = 'SAVE_CUSTOMER_INIT'
export const SAVE_CUSTOMER_SUCCESS = 'SAVE_CUSTOMER_SUCCESS'
export const SAVE_CUSTOMER_FAILURE = 'SAVE_CUSTOMER_FAILURE'
export const UPDATE_CUSTOMER_INIT = 'UPDATE_CUSTOMER_INIT'
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS'
export const UPDATE_CUSTOMER_FAILURE = 'UPDATE_CUSTOMER_FAILURE'

// Articles Actions(Async)
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS'
export const FETCH_ARTICLES_FAILURE = 'FETCH_ARTICLES_FAILURE'
export const FETCH_ARTICLE_SUCCESS = 'FETCH_ARTICLE_SUCCESS'
export const FETCH_ARTICLE_FAILURE = 'FETCH_ARTICLE_FAILURE'
export const SAVE_ARTICLE_SUCCESS = 'SAVE_ARTICLE_SUCCESS'
export const SAVE_ARTICLE_FAILURE = 'SAVE_ARTICLE_FAILURE'